#
# Source: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
# Run GHA workflow on PR comment
#


# Source: https://stackoverflow.com/questions/70699702/triggering-action-by-pr-comment-action-dosnt-return-status

name: PR commented

# See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review_comment
# Use job outputs as in https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs#overview

### ONLY RUNS IF FILE IS DEFAULT BRANCH ###
on:
  issue_comment:
    types: [created, edited]

jobs:
  # extract GHA context and prepare output for other jobs
  prepare-gha-context:
    runs-on: ubuntu-latest
    outputs:
      event_name: ${{steps.identify.outputs.event_name}}
      comment_body: ${{steps.identify.outputs.comment_body}}
    steps:
      - name: extract GH context into outpu
        id: identify
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          # use jq to extract into bash variables
          export EVENT_NAME=$(echo "$GITHUB_CONTEXT" |  jq -r .event_name )
          export COMMENT_BODY=$(echo "$GITHUB_CONTEXT" | jq -r .event.comment.body )

          echo "::set-output name=event_name::${EVENT_NAME}"
          echo "::set-output name=comment_body::${COMMENT_BODY}"

          echo "Got this GH event:$EVENT_NAME: with this comment:$COMMENT_BODY:"
          # echo "$GITHUB_CONTEXT"

  pr-comment:
    runs-on: ubuntu-latest
    needs: prepare-gha-context
    if: ${{ needs.prepare-gha-context.outputs.event_name}} == issue_comment
    steps:
      - name: normal-pr-comment
        run: |
          echo "Saw comment PR comment :${{ needs.prepare-gha-context.outputs.event_name}}:"

  pr-comment-ok:
    needs: prepare-gha-context
    runs-on: ubuntu-latest
    if: ( ${{ needs.prepare-gha-context.outputs.event_name }} == issue_comment &&  contains(needs.prepare-gha-context.outputs.comment_body, 'ok') )
    steps:
      - name: ok-pr-comment
        run: |
          echo "Saw OK-comment :${{needs.prepare-gha-context.outputs.comment_body}}:"
          echo "Going to set GHA trigger"

# on: issue_comment

# jobs:
#   pr_commented:
#     # This job only runs for pull request comments
#     name: PR comment
#     if: ${{ github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo A comment on PR $NUMBER
#         env:
#           NUMBER: ${{ github.event.issue.number }}

#   issue_commented:
#     # This job only runs for issue comments
#     name: Issue comment
#     if: ${{ !github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo A comment on issue $NUMBER
#         env:
#           NUMBER: ${{ github.event.issue.number }}
