#
# Source: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
# Run GHA workflow on PR comment
#


# Source: https://stackoverflow.com/questions/70699702/triggering-action-by-pr-comment-action-dosnt-return-status

name: PR commented

# See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review_comment
# GHA runs even on non-default branches
on:
  issue_comment:
    types: [created, edited]

jobs:
  gha-context:
    runs-on: ubuntu-latest
    steps:
      - name: show GH context
        env:
          GITHUB_CONTEXT: ${{ github }}
        run: echo "$GITHUB_CONTEXT"

  pr-comment:
    if: ${{ (github.event.issue.comment.body ) }}
    runs-on: ubuntu-latest
    steps:
      - name: normal-pr-comment
        run: |
          echo "Saw comment PR comment."
          echo "${{github.event.comment.body}}"

  pr-comment-ok:
    if: ${{ (github.event.issue.comment.body ) && contains(github.event.comment.body, 'ok') }}
    runs-on: ubuntu-latest
    steps:
      - name: ok-pr-comment
        run: |
          echo "Saw comment 'ok'!"
          echo "${{github.event.comment.body}}"

# on: issue_comment

# jobs:
#   pr_commented:
#     # This job only runs for pull request comments
#     name: PR comment
#     if: ${{ github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo A comment on PR $NUMBER
#         env:
#           NUMBER: ${{ github.event.issue.number }}

#   issue_commented:
#     # This job only runs for issue comments
#     name: Issue comment
#     if: ${{ !github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo A comment on issue $NUMBER
#         env:
#           NUMBER: ${{ github.event.issue.number }}
