#
# Source: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
# Run GHA workflow on PR comment
#


# Source: https://stackoverflow.com/questions/70699702/triggering-action-by-pr-comment-action-dosnt-return-status

name: PR commented

# See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review_comment
# GHA runs even on non-default branches
on:
  issue_comment:
    types: [created, edited]
# env values will be overwritten in first job
env:
  EVENT_NAME: NOOP
  COMMENT_BODY: NOTHING

jobs:
  prepare-gha-context:
    runs-on: ubuntu-latest
    steps:
      - name: extract GH context into environment variables
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          EVENT_NAME=$(echo "$GITHUB_CONTEXT" |  jq -r .event_name )
          COMMENT_BODY=$(echo "$GITHUB_CONTEXT" | jq -r .event.comment.body )
          echo "EVENT_NAME=${EVENT_NAME} >> $GITHUB_ENV"
          echo "COMMENT_BODY=${COMMENT_BODY} >> $GITHUB_ENV"
          echo "Got this GH event:$EVENT_NAME: with this comment:$COMMENT_BODY:"
          # echo "$GITHUB_CONTEXT"

  pr-comment:
    needs: prepare-gha-context
    runs-on: ubuntu-latest
    if: ${{ env.EVENT_NAME == issue_comment ) }}
    steps:
      - name: normal-pr-comment
        run: |
          echo "Saw comment PR comment :${{env.COMMENT_BODY}}:"

  pr-comment-ok:
    needs: prepare-gha-context
    runs-on: ubuntu-latest
    if: ${{ env.EVENT_NAME == issue_comment ) }} && contains(${{env.COMMENT_BODY}} 'ok') }}
    steps:
      - name: ok-pr-comment
        run: |
          echo "Saw OK-comment :${{env.COMMENT_BODY}}:"
          echo "Going to set GHA trigger"

# on: issue_comment

# jobs:
#   pr_commented:
#     # This job only runs for pull request comments
#     name: PR comment
#     if: ${{ github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo A comment on PR $NUMBER
#         env:
#           NUMBER: ${{ github.event.issue.number }}

#   issue_commented:
#     # This job only runs for issue comments
#     name: Issue comment
#     if: ${{ !github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo A comment on issue $NUMBER
#         env:
#           NUMBER: ${{ github.event.issue.number }}
